### ISSUE TITLE
Linux version for truenas scale

### ISSUE THREAD

**Issue by lordraiden** [ngandrass/truenas-spindown-timer#12]
Can you make a version compatible with truenas scale?

**Comment by ngandrass** [comment]
Hi lordraiden,

I'd like to make the script compatible with TrueNAS SCALE, but currently have no system to test it on. This will probably change within the next weeks.

To make the script work on SCALE replacing all `camcontrol` calls with equivalent calls should in theory be enough. I'll see if I can do a first smoke test using a SCALE VM.

Do you have access to a TrueNAS SCALE box to test a version of the script on?

Kind regards :)

**Comment by ngandrass** [comment]
Relates to #8

Note to self: Should check out the mentioned adapted script version prior to implementation.

**Comment by fdzaebel** [comment]
I also would love to see a version running on SCALE.

**Comment by Hafnernuss** [comment]
Maybe this can help:
https://github.com/sretalla/freenas-spindown-timer/blob/master/spindown_timer_SCALE.sh

**Comment by ngandrass** [comment]
Hey folks, check out the latest release v2.0.1 - I successfully tested it today on TrueNAS SCALE :)

See: https://github.com/ngandrass/truenas-spindown-timer/releases/tag/v2.0.1
