### ISSUE TITLE
Not working in TrueNAS 13.1

### ISSUE THREAD

**Issue by marcocipriani01** [ngandrass/truenas-spindown-timer#13]
Hello,
I'm having trouble using the script on my TrueNAS Core 13.1 NAS with three Seagate IronWolf SATA hard disks. As to be expected, the built-in TrueNAS spindown/power saving feature doesn't actually work, so I downloaded the spindown script in `/root/` and ran

```
chmod +x spindown_timer.sh
spindown_timer.sh -t 3600 -p 600 -v
```

My drives all showed up as `ada0`, `ada1` and `ada2`, and the script started waiting for the HDD activity to go down. So I closed all the Samba and Nextcloud applications connected to the NAS (I'm pretty sure nothing was using the NAS at that point) and waited. In another shell, I repeatedly ran

```
camcontrol epc ada0 -c status -P
camcontrol epc ada1 -c status -P
camcontrol epc ada2 -c status -P
```

but I never got `Standby_z`. I always get `Idle`, and I can still hear the drives spinning. If I stop the spindown script and run `camcontrol standby ada0`, the first drive stops spinning and I get `Standby_z`. The drive doesn't spin up again until I reconnect to the NAS with some application or some SMART check inevitably spins it up again. This makes me think that the way the script checks for activity isn't compatible with TrueNAS 13.1, since the `camcontrol standby` command still works just fine.

Do you have any idea why it doesn't work? Can you replicate the issue on a TrueNAS 13.1 installation?
Thanks

**Comment by ngandrass** [comment]
Hi,

my box is currently running on 12.0-U8.1 but changes are good that I can find some time to upgrade it to the current stable version 13.0-U2 tomorrow. In the meantime: Can you provide the output of the script in verbose mode (`-v`)? This should show if the problem lies in the idle detection or the spindown command.

Thanks! :)

**Comment by marcocipriani01** [comment]
Thanks, here are some logs from your script:

![IMG-20221015-WA0010](https://user-images.githubusercontent.com/20319029/196033099-b752f32a-efc9-4324-897c-fa1b9e51ce3c.jpg)

Manually spinning down a disk works if I use the `camcontrol standby ada0` command, so I think the problem is in the activity detection.

**Comment by ngandrass** [comment]
Thank you for providing the information. I upgraded my system to the latest stable TrueNAS-13.0-U2 today. However, I wasn't able to reproduce your problem. My disks spun down without problems. You seem to use a beta release of TrueNAS, which I currently cannot deploy on my system. It might use a newer version of `iostat` ...

You are right. The problem indeed lies in `iostat` not considering your drives as idle. Please check the following:

1. Your system dataset is **not** located on any of the disks
2. You don't have any VMs running on the disks
3. You have set S.M.A.R.T. Power Mode to Standby (Services -> S.M.A.R.T)

You can also execute `iostat` manually to check if the error occurs during parsing the `iostat` output or if there actually is I/O on the disks. To wait for 60 seconds and list all drives with I/O please execute the following command: `iostat -x -z -d 60 2`

You can adjust the time period (here 60 seconds) to your needs but remember that some I/O can be irregular. The spindown script therefore uses a default poll-time of 600 seconds (10 minutes).

Please provide the full output of the above command. I might be able to make adjustments to the script if the format of the `iostat` output changed.

Thanks! :)

**Comment by marcocipriani01** [comment]
My bad, I have TrueNAS 13.0-U1, not 13.1. I will check all those things (maybe I have a VM running, I can't remember), try running `iostat` manually, update to 13.0-U2 and let you know! Thank you very much

**Comment by ngandrass** [comment]
If a VM is indeed the problem, you can move the associated storage devices onto the same pool as your system dataset is on :)

**Comment by marcocipriani01** [comment]
I'll look into that in a couple of days, do you know of some tutorial/guide on how to move a VM to the system dataset or boot drive (I have a NVMe SSD for boot)?

**Comment by ngandrass** [comment]
Never did that myself, but I guess it boils down to moving the data from the old dataset to a new one. During a quick search I found some folks fiddling around with this: https://www.truenas.com/community/threads/move-vm-from-hdd-to-ssd.93704/

**Comment by marcocipriani01** [comment]
Hi, I did all the tests you suggested and finally found the culprit. I don't have any VM running, but I have two jails, one for NextCloud and one for my IDrive cloud backups. As it turned out, the IDrive backup jail constantly scans the drives for file changes, keeping them on. I disabled that jail and now everything is working as it should. Thank you for your time and help!

**Comment by ngandrass** [comment]
I'm glad to hear that everything is working fine for you now.

Thanks for explaining the problem. Maybe this can be helpful to someone in the future :)
