### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by sp00ktober** [ngandrass/truenas-spindown-timer#16]
I installed TrueNAS CORE a few days ago on my newly build setup, and as it will only be used a few times a day at max but still should be powered on all the time i really want to spindown the HDDs (to reduce the noice mostly).

However running the spindown script (even without arguments) just gives me
`: No such file or directory` as an error. Im not sure if i deployed it wrong or if i am missing something.

Would be great to get some input here :)

**Comment by ngandrass** [comment]
Invoking the script without any additional arguments (e.g. running `./spindown_timer.sh`) should monitor all drives that it detects. A good way to check if the script is executable is to run the following command: `./spindown_timer.sh -h`. It should print the help text.

Could you please try running the script in verbose mode (executing: `./spindown_timer.sh -v`) and paste both the invocation and the script output here? The easiest way should be a screenshot of the terminal with script execution and output.

Thanks! :)

**Comment by sp00ktober** [comment]
Thanks for the reply, here is the screenshot :)
![grafik](https://user-images.githubusercontent.com/79335616/206051748-7849b197-ec8b-4877-b071-0296b2cbfb34.png)

**Comment by ngandrass** [comment]
Thanks!

1. Please confirm that the spindown script is actually placed inside the current folder and the executable bit is set. This can be done via `ls -lah /mnt/Datengrab/Storage1/Maintenance | grep spindown`.
2. Does `./spindown_timer.sh -h` produce a different output? If so, some program the script relies on seems to be unavailable on your system.

**Comment by sp00ktober** [comment]
the script is at that place, and it has the flag set. `-h` does produce the same output.
![grafik](https://user-images.githubusercontent.com/79335616/206052816-42b9143c-c01a-4a34-9598-02fb496bc420.png)

**Comment by ngandrass** [comment]
I performed a fresh install of `TrueNAS CORE 13.0-U3.1` and deployed the spindown script. Executing `./spindown_timer.sh -h` produced a valid output, so I was unable to reproduce the error you encounter.

Please confirm that your `spindown_timer.sh` script has the following sha256 checksum: `22ee207eeec00053002a0d22fd38fa699ecf7613530207f1b820507a21dc1c01`

```
root@truenas[~]# sha256sum spindown_timer.sh
22ee207eeec00053002a0d22fd38fa699ecf7613530207f1b820507a21dc1c01  spindown_timer.sh
```

**Comment by sp00ktober** [comment]
now i feel bad about this. I checked the sha256 hash and it was indeed off, there must have been some issue copying the script over. Downloaded it again and now the hash matches and i can execute the script.

guess you can close this, and thanks for your effort!

**Comment by ngandrass** [comment]
No need to feel bad about it. I'm glad to hear that it works for you now :)
