### ISSUE TITLE
[ERROR]: No supported disk parameter tool found.

### ISSUE THREAD

**Issue by JakobEdvardsson** [ngandrass/truenas-spindown-timer#19]

**Comment by JakobEdvardsson** [comment]
Got it to partially fixed, my bad

**Comment by ngandrass** [comment]
The bug report seems to be empty. Could you please describe the error?

**Comment by JakobEdvardsson** [comment]
Sorry I think I figured it out and I wasn't able to delete the issue. My bad!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by henne49** [comment]
I have the same error, what tool do I need to install on truenas scale?

**Comment by JakobEdvardsson** [comment]
> I have the same error, what tool do I need to install on truenas scale?

Sorry I don't recall. Switched to Unraid

**Comment by ngandrass** [comment]
TrueNAS Scale uses `hdparm`. However, it should be installed by default. Please check if it is available.

**Comment by henne49** [comment]
yes, it is but only when using as root. the script is now in use. Thank you

**Comment by Darksk0pe** [comment]
missing hdparm to on 25.04 truenas 

truenas_admin@truenas[/mnt/System/Files/spindown]$ ./spindown_timer.sh -d -c -p 60
[2025-04-25 10:25:53] Performing a dry run...
[2025-04-25 10:25:53] [ERROR]: No supported disk control tool found.
[2025-04-25 10:25:53] [ERROR]: No applicable control tool found. Exiting...

truenas_admin@truenas[/mnt/System/Files/spindown]$ hdparm
zsh: command not found: hdparm

**Comment by ngandrass** [comment]
Hehe, maybe we should add a proper detection mechanism that checks if the script is running without the required privileges since some users are seemingly running into this issue. I'll put it on my list.

**Comment by ngandrass** [comment]
I created #50 to introduce an error message if the script is not run as root.

**Comment by tp-1400** [comment]
ok. running the script via as root is working. However, how do I manage that when it is run automatically after boot?

**Comment by ngandrass** [comment]
If you register it as a post-init script via the GUI it is run as root automatically :)
