### ISSUE TITLE
Some communication about integrating the script into the TrueNAS mainline

### ISSUE THREAD

**Issue by GoingTime** [ngandrass/truenas-spindown-timer#20]
Hi ngandrass,

I raised a Jira ticket "[Request to add the hard disk automatic standby function based on hard disk usage monitoring](https://ixsystems.atlassian.net/browse/NAS-121579)". The staff of iX-Systems suggested that they can provide some technical support for this script. If the script is reliable enough, they may integrate the script into the TrueNAS mainline. A faster way is to work with the TrueCharts community to allow scripts to be deployed as Docker containers.

Do you have any interest, thanks :)

**Comment by ngandrass** [comment]
Hi,

thanks for raising the spindown topic at iXsystems with your ticket and providing valuable information :) However, I'm not sure if I fully understand your goal with this.

Do you want to improve deployment of this script by providing it as a plugin (CORE) or docker container (SCALE)? Do you want to see it integrated into the TrueNAS mainline code? Would you like to see additional features like the mentioned upper limit for spindowns per 24 hours?

**Comment by ngandrass** [comment]
Porting the scripts functionality to Python should be no big deal and is something I could do. I initially just decided against using Python for the job to keep the script as system-independent as possible. But over time it evolved to be a full TrueNAS-specific thing anyway I guess ;)

On the other hand side: I just had a quick look into BSD jail permissions and the TrueNAS CORE plugin ecosystem. I should be able to package everything in a way that we could integrate it as an official community plugin. And I'm sure the same would go for TrueNAS SCALE. This would allow us to have a simple one-click install.

I think that would be a great way to improve usability for everyone. And keeping the spindown timer code separate from TrueNAS mainline code would allow us to release improvements and fixes more easily. What do you think?

**Comment by Sophist-UK** [comment]
I think we can understand why TrueNas focuses on adding enterprise functionality because that is where the $$ are - TBH we home users are darn lucky to have a NAS O/S of this quality made available to us for free!!

Personally I didn't find the implementation of this script too complex - but then I am an IT technical type with Linux experience. And I am not certain that  using a TrueChart package is going to be that much easier for a user to implement.

**Logging**: I am not sure that logging is related to use of a script or of a TrueCharts package - but I do agree that logging to Syslog would be a good thing and I assume that this is possible using bash scripts.

**Comment by ngandrass** [comment]
>I am not certain that using a TrueChart package is going to be that much easier for a user to implement.

Sadly, that is exactly my conclusion with this topic. I spent multiple hours trying to fiddle around with the plugin infrastructure of TrueNAS (or more precisely, `iocage`).

I managed to deploy the script as a TrueNAS plugin (basically a jail with some extra scripts). However, I found no easy way to expose any custom settings via the TrueNAS GUI, hereby forcing the users to modify settings tediously via shell commands. The only way I found would be to provide a whole webservice just to manage the plugin settings. And this is **way** beyond the scope of a, let's face it, sophisticated shell script. Therefore, I won't release an official plugin for the Spindown Timer as of now.

If anyone finds a good way of fully integrating custom settings within the TrueNAS Plugin GUI please feel free to re-open this issue. I'd be more than grateful for input on this topic :)

**Comment by Sophist-UK** [comment]
I think this is best handled by providing clearer instructions for the less technical of us. I am happy to do that for TrueNas Scale (if someone can then tweak them for TrueNas Core which I have no experience of).
