### ISSUE TITLE
Script not working / claiming wrong drives

### ISSUE THREAD

**Issue by d22b** [ngandrass/truenas-spindown-timer#21]
Hi there,

thanks for contributing that kind of script.

I would like to spin down my zfs pool when not in use. Unfortunately the command seems to be claiming the wrong drives. What i am doing wrong?

root@truenas[/home/admin/truenas-spindown-timer-2.2.0]# ./spindown_timer.sh -t 60 -p 60 -u zpool -i Archive
[2023-04-26 12:54:39] Monitoring drives with a timeout of 60 seconds: sdb
[2023-04-26 12:54:39] I/O check sample period: 60 sec

Which is wrong. The pool Archive is about sde,sdf,sdd

TrueNAS-SCALE-22.12.2

**Comment by ngandrass** [comment]
**TL;DR:** Add `-m` to your arguments.

-----------------

Hi there,

in both cases you are using auto detection mode (default) which ignores the given pools / drives.

The `-i` argument is used to **ignore** the given drives. If you also supply `-m`, the drives specified via `-i` will be explicitly selected (this is what you need here). See the usage information inside the README or displayed by invoking the script with `--help`:
```
  -i DRIVE     : In automatic drive detection mode (default):
                   Ignores the given drive or zfs pool.
                 In manual mode [-m]:
                   Only monitor the specified drives or zfs pools. Multiple
                   drives or zfs pools can be given by repeating the -i option.
  -m           : Manual drive detection mode. If set, automatic drive detection
                 is disabled.
                 CAUTION: This inverts the -i option, which can then be used to
                 manually supply drives or zfs pools to monitor. All other drives
```

**Comment by ngandrass** [comment]
I'm glad to hear that it works for you :)

I'll close this issue but feel free to open another issue if you encounter further problems!
