### ISSUE TITLE
HDD dont like to be sleeping to long (max 4 Minutes)

### ISSUE THREAD

**Issue by d22b** [ngandrass/truenas-spindown-timer#22]
Sorry, me again.

HDD Spindown works perfect. Unfortunately the disks are waking up after a couple of minutes without using the system. What i have done:

- followed your Instruction and set HDDS to always on | Value to 128
- moved system to boot partition
- disabled any service (including SMART)

**Comment by pojlFDlxCOvZ4Kg8y1l4** [comment]
I would like to confirm this, behaviour shows waking every 5 minutes. 
Also disk IO graphs show a "peak" at those intervals, pretty much always small reads and nothing else.  
Maybe this helps other people find this bug report, it took way too long for me to figure this out. 

![image](https://github.com/ngandrass/truenas-spindown-timer/assets/42654642/da619452-c8e2-4b73-8347-7f5d5198d448)

**Comment by ngandrass** [comment]
Related to #14
