### ISSUE TITLE
Doesn't seem to be working

### ISSUE THREAD

**Issue by sagang227** [ngandrass/truenas-spindown-timer#23]
Thank you for this script. I am new to TrueNAS Core and implemented your script by following your intruction. Below are the steps I took. TrueNAS Core version is 13.0-U5.1.

- Created **/root/scripts/** folder and copied your script via SCP(this was the most difficult part for a newb, let me know if I did it wrong).
- Set **system dataset** to **boot-pool**(SSD).
- Set **HDD Standby** to **Alway On**, **APM** to **128**. Also set **Power Mode** to **Standby** after intial try without it didn't work.
- Created **Init Script** with command **/root/scripts/spindown_timer.sh -t 600 -p 100 -i ada1 -s 3600**. ada1 is the boot SSD.

The disk is not spinning down after 10 mins and the system doesn't shut down after 1 hour. I have Plex server installed and intention was to shut the server down after I'm done watching it. The pool is also shared on SMB but I tried testing it by not accessing the share and letting the server sit idle for hours.

Please let me know if I'm doing anything wrong, thanks.

**Comment by ngandrass** [comment]
Hi,

please run the spindown timer in verbose mode (adding `-v` flag) and provide the output. This way the script shows all detected drives as well as if it detected I/O during the poll intervals.

First thoughts:
1. On which drive is `/root/scripts/` located?
2. Can it be possible that Plex accesses the media files on a regular basis, hence blocking the spindown?

**Comment by sagang227** [comment]
Hi Niels,

Thanks for the support. Below are the answers to your questions and the output of the script.

1. /root/scripts/ is installed on the boot SSD I believe. I'm a beginner so please let me know if there is a command to verify this.
2. I think that's very possible. If so, is there a way to move Plex to the SSD and have it only access the HDD when it is actually playing the video?

![Screenshot 2023-07-15 111724](https://github.com/ngandrass/truenas-spindown-timer/assets/139574562/7d67403b-7413-4d97-81e5-8a9284e04d86)

**Comment by ngandrass** [comment]
Thanks for the information! It indeed looks like the script, or more precisely the underlying `iostat` call, detects I/O on `ada0`. If no I/O was detected during a poll interval, the drive timeout should decrease by the length of the poll interval in seconds.

 -----

> 1. /root/scripts/ is installed on the boot SSD I believe. I'm a beginner so please let me know if there is a command to verify this.

That sound fine :)

-----

> 2. I think that's very possible. If so, is there a way to move Plex to the SSD and have it only access the HDD when it is actually playing the video?

You probably have installed Plex via the TrueNAS plugin manager. This would create a Jail that is located at the location you have configured under `Jails > Choose Pool for Jail and Plugin Manager`:

![image](https://github.com/ngandrass/truenas-spindown-timer/assets/326180/d00b87cd-f918-4c0c-912c-d149bfbd7472)
![image](https://github.com/ngandrass/truenas-spindown-timer/assets/326180/b7aebcf8-b503-4ca5-b5aa-547f911c63fa)

Please verify that the jail is located on your `ada1` drive pool.

**Comment by sagang227** [comment]
1. I assume it's incorrect that I/O is detected on ada0? ada0 is the drive I want to spindown, and the timeout timer is not decreasing. How can I fix this?
2. I followed your steps and verified that Plex jail is on ada0 HDD. ada1 is my boot drive so it doesn't let me move it to the boot drive. I found out that there are workarounds to partition my boot drive to 2 pools and install jails on the boot SSD, but it is a bit complicated for my level. Do you think this is what's preventing me from shutting down the system? 

Thanks!

**Comment by ngandrass** [comment]
The problem is that your Plex jail (and all other potential jails) is located on `ada0`. This will inevitably cause I/O on `ada0` and will prevent the drive from spinning down. You can only spin down idle drives.

If you want to spin down `ada0` you **must** move your jails to another pool. This, for example, can be another SSD.

**Comment by sagang227** [comment]
Thanks, I finally understand it! I'll try this later when I have more time to learn and split the boot drive to two pools. It seems doable.

**Comment by ngandrass** [comment]
Have you had any success in getting this to work? Can this issue be closed?

**Comment by sagang227** [comment]
I haven't got around testing it yet but I think I know the problem now. I'll close it, thanks again!

**Comment by ngandrass** [comment]
Ok. Feel free to re-open this issue if you encounter further problems :)
