### ISSUE TITLE
[Request] Use `logger` to log output to Syslog

### ISSUE THREAD

**Issue by Sophist-UK** [ngandrass/truenas-spindown-timer#27]
1. Use the `logger` command to log to syslog every time `echo` is used. (`-d` changes the default to off.)
2. Perhaps have a `-l` switch that can be used to toggle the default.

(Note: Ideas inspired by https://github.com/lynix/hdd-spindown.sh/blob/master/hdd-spindown.sh .)

**Comment by ngandrass** [comment]
Thanks for your suggestion!

Sounds like a useful addition. I'll integrate it within the next days and release an update version :)

**Comment by ngandrass** [comment]
I integrated the syslog mode (`-l`) into the `develop` branch: https://github.com/ngandrass/truenas-spindown-timer/tree/develop

The README.md is updated accordingly. Please verify that this suites your needs :)
