### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by sylv3rblade** [ngandrass/truenas-spindown-timer#28]
Hi ngrandrass I added the spin down script to root/scripts/spindown_timer.sh but I am getting these errors when running it on the latest version of Truenas Core `TrueNAS-13.0-U5.3`

```
root@providence[~/scripts]# /root/scripts/spindown_timer.sh -v -t 1200 -p 300 -m -i da1 -i  da2 -i da3 -i da4 -i da5 > /var/log/spindown.log
Assembler messages:
Error: can't open idle for reading: No such file or directory
idle: Error: can't open POLL_TIME=600 for reading: No such file or directory
/root/scripts/spindown_timer.sh: line 38: mode: command not found
/root/scripts/spindown_timer.sh: line 39: verbosity: command not found
```

**Comment by ngandrass** [comment]
Hi,

this is weird... I updated my machine to `TrueNAS-13.0-U5.3` and have no issue :/

Please verify that your `spindown_timer.sh` script is deployed correctly by validating its SHA256 checksum:

```bash
sha256sum /root/scripts/spindown_timer.sh
```

It must equal `6c00ed442a651ad2f827e5de8b8a075a317f312189762ed69c81fddff02669ea`

Thanks!

**Comment by sylv3rblade** [comment]
ah thank you, I got a different checksum.  I ssh'd into my truenas box and recreated the file (i think I just did it via the truenas shell in the ui).

its working now

**Comment by ngandrass** [comment]
Awesome. Thanks for your quick feedback :heart:
